### ISSUE TITLE
Quiz Page

### ISSUE THREAD

**Issue by AchimBartscht** [alinarub/dog-app#1]
## Value proposition
**As a user** I want to start the quiz and be taken through seven questions. I can only choose one answer. The progress bar indicates how many more questions I still have to answer. If I select an answer, I can still change my mind and navigate back and forth with the "previous" and "next" buttons.
**In order to** find out which dog matches my needs.
## Description

![ga-neueFische-hunde-app-v003](https://github.com/alinarub/dog-app/assets/132458107/9da96b1d-d2b4-4d5c-8b8c-a08bdf5e2c84)

## Acceptance criteria
- [ ] On top of the page, an intro text guides the user on how to use the quiz.
- [ ] Each of the seven questions offers five different answers (via buttons).
- [ ] You have to select one answer, and you can´t choose more than one.
- [ ] The selection of one answer is visually indicated by a coloured border.
- [ ] Even after an answer is selected you still need to confirm by clicking on the "next" button. You only can click the "next" button if you selected one answer.
- [ ] With the "previous" and "next" buttons you can see which answers you have selected. You can choose another answer by clicking on it.
- [ ] There is no "previous" button needed on the first site of the quiz.
- [ ] There is no "next" button needed on the last site of the quiz.

## Tasks
- [ ] Create the feature branch `quiz`.
- [ ] ? Most likely the fetching process takes place after the user has answered all seven questions. Don't forget error handling.
- [ ] Create the component `introText`.
- [ ] Create the component `quizForm` (includes all seven questions, only one question being shown at a  time).
- - [ ] Add a question at the top of the form.
- - [ ] Make the selected answer appear with a border in the accent color.
- - [ ] Create the component `progressBar`.
- - [ ] Create the components `previousButton` and `nextButton` - navigation is only possible when an answer is selected.

The logic of the filter functionality will be implemented in its own user story.

**Comment by alhen002** [comment]
Nice work so far. 
I guess the value proposition could be a bit shorter. I really like your detailed acceptance criteria.

**Comment by gregorsart** [comment]
We have split this user story into three little user stories.
