### ISSUE TITLE
Results Page // Basic setup

### ISSUE THREAD

**Issue by alinarub** [alinarub/dog-app#10]
## Value proposition
**As a user** 
I want to see the results of the quiz.

**In order** to find the right dog.

## Description
![Image](https://github.com/alinarub/dog-app/assets/137082094/8892aad0-18dd-4fc0-91c7-9cd16ddd824c)
 
## Acceptance criteria
- [ ] The three dog breeds that match my chosen answers best are displayed.
- [ ] The style of the components and the whole page is consistent with the other pages.

 
## Tasks
- [ ] Create the feature branch `results-page`.
- [ ] Use the `TextImage` component to display the intro text.
- [ ] Use the `Headline` component to display "Results".
- [ ] Use the `FullWidthButton` component to display the best matching dog breeds.
- [ ] Create three links to the `detailsPage`.
- [ ] Move `dummyDogs`, `assignPointsToDogs` and `calculateAssignedPoints` to a a utils folder.

**Comment by NikRoe** [comment]
Hi there,

this looks really great already!

There is one question I am still wondering about:
What happens when a user clicks on a breed? Will they be redirected to a details page?

Best regards 👋

**Comment by fel-sad** [comment]
Hey Y'all, love the idea and concept of the app! 

Maybe as consideration for a future user story or this: after clicking the link to the detail page of the three dog breeds: Can users go back to explore their results or would they have to take the quiz again?

Cheers ✌️

**Comment by alinarub** [comment]
Our backend changed so we didn't need some things anymore such as the last task.
