### ISSUE TITLE
FAQ Page

### ISSUE THREAD

**Issue by alinarub** [alinarub/dog-app#11]
## Value proposition
**As a user** 
I want to read more about how the app works.

**In order** to know how to understand the results.

## Description
![Image](https://github.com/alinarub/dog-app/assets/137082094/4b3c5061-6202-4c34-bb53-6db1c73bc2af)
 
## Acceptance criteria
- [ ] The most important questions are answered. 
 
## Tasks
- [ ] Create the feature branch `faq`.
- [ ] Create an accordion to list all the FAQs in a user-friendly way.

**Comment by NikRoe** [comment]
Hi there,

Will all questions including answers be visible at all times or will they be collapsible? 

Will the FAQ be on a different page? And if so, how can a user navigate between the different pages?

This is something you could add to your Acceptance Criteria.

Best regards 👋

**Comment by fel-sad** [comment]
Looks good to me. 😄
