### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by alinarub** [alinarub/dog-app#15]
## Value proposition
**As a user** 
I want to click on the header

**in order** to navigate the app.

## Description
![Image](https://github.com/alinarub/dog-app/assets/137082094/24bb3171-7de7-4ea3-a676-4b510f30b56f)

## Acceptance criteria
- [ ] The header is always displayed on every page.
- [ ] The app name is in the middle.
- [ ] By clicking on the logo, you get back to the home page.
- [ ] The hamburger button is part of the header but isn't usable yet.

## Tasks
- [ ] Create the feature branch `header`.
- [ ] Create the component `Header`.
- [ ] Create the `Logo` component and make it a link to the home page.
- [ ] Create the hamburger button, but leave it non-functional for now.

**Comment by fel-sad** [comment]
Looks good to me! I'll give the userstory a ✅ but I think, that adding the button for the burger menu without any functionality is a bit counter intuitive. I would suggest removing the button for now and adding it to the header, when it serves a purpose. 🙌
