### ISSUE TITLE
Detail Page

### ISSUE THREAD

**Issue by alinarub** [alinarub/dog-app#2]
## Value proposition
**As a user** I want to get detailed information on the dog that was suggested to me by the quiz result.

**In order to** see if the dog really is a good fit.

## Description
![Bildschirmfoto 2023-10-12 um 09 58 46](https://github.com/alinarub/dog-app/assets/137082094/a0b53fce-0ead-4d4a-a2c2-8a99b7db1b18)

## Acceptance criteria
- [ ] All displayed information comes from the API
- [ ] Show the picture of the dog breed at the top of the screen
- [ ] Below the picture, all seven characteristics asked about in the quiz are displayed with the x/5 rating.
- [ ] By clicking on the "more" button, the other 5 characteristics are also displayed, if possible also with the x/5 rating
- [ ] The "back" button brings you back to the quiz result

## Tasks
- [ ] Fetch all necessary information including the picture from the API
- [ ] Set up dynamic routing, so that each of the 200 dog breeds has its own detail page
- [ ] Create the component `button`, which can be used for the "back" and "more" buttons
- [ ] Create a `ul` for both the seven quiz characteristics and the additional information displayed on the "more" page, that includes the rating

**Comment by NikRoe** [comment]
Hi there,

promising start!

The wireframe displays a burger menu, will that menu already have functionality? Otherwise I would remove it from the wireframe.

And your value proposition could be even shorter:
As a user 
I want to get detailed information on the suggested dog,
In order to see if the dog really is a good fit.

Best regards 👋

**Comment by NikRoe** [comment]
LGTM
