### ISSUE TITLE
All Dogs // Basic search function

### ISSUE THREAD

**Issue by alinarub** [alinarub/dog-app#22]
## Value proposition
**As a user** I want to search for a specific dog by name

**In order** to find out more about them.

## Description
![Image](https://github.com/alinarub/dog-app/assets/137082094/93b67ba7-bbfe-4980-b7bd-b97aeb6f664e)

 
## Acceptance criteria
- [ ] By typing in a letter, I want all dogs that start with that letter to be shown in my list.
- [ ] All dogs that are shown can be clicked, which leads to their detail page.
- [ ] The only thing that changes on the All dogs page is the amount of dogs shown.
 
## Tasks
- [ ] Create the feature branch `basic-search`.
- [ ] Create the component `Search`.
- [ ] Use the existing component `AllDogsCard` to display the filtered dogs.
- [ ] Implement basic filter logic.

**Comment by alinarub** [comment]
Hi Jessica, thank you for reviewing and for your great ideas! We added them to the user story.
