### ISSUE TITLE
Results Page Redesign

### ISSUE THREAD

**Issue by alinarub** [alinarub/dog-app#29]
## Value proposition
**As a user** I want to have a more visually appealing results page

**In order** to enjoy seeing my results more.

## Description
Current version that will be changed as we go along:
![Image](https://github.com/alinarub/dog-app/assets/137082094/d69da4d1-52e3-41a7-b95f-f58eca02c077)

 
## Acceptance criteria
- [ ] The results are shown with less scrolling.
- [ ] There is less blank space in the cards.
- [ ] The image of the dog should still be recognizable, so it cannot be too small.
- [ ] Confetti appears when you first reach the `results page`.
 
## Tasks
- [ ] Create the feature branch `results-page-redesign`.
- [ ] Redesign `DogCard.js`
- [ ] Add confetti to the page.
- [ ] Reduce margin-top above the `ImageTextModule`.

**Comment by Julia-Pickel** [comment]
Hi there!

I really like that you want to work on the design of your result page to make it even more user friendly! 🙌 

Since there is only an image of your current design it's a bit difficult to fully get what you're planning to change.
But here some suggestions and thoughts on your user story:

### Value proposition
> As a user I want to have a more visually appealing results page
> in order to enjoy seeing my results more.

**Suggestion** ⬇️ 
As a user
I want to have a nice and clean overview of my quiz results
so that I enjoy my matching dogs even more


### AC
> The results are shown with less scrolling and in a more space-efficient way.

→ What do you mean by that? And how are you going to change this?

**Suggestion** ⬇️ 
AC:
– There is a brief overview of all suggested dogs in which each dog is displayed as a card 
Task:
– Change style of `ul` component (e.g. display `ul` as grid and set `place-content` on center) 
– Reduce `margin` of image component 


>  Confetti appears when you first reach the results-page.

→ Nice feature 🤩 🎊

**Comment by AchimBartscht** [comment]
Thank you, Julia. We added most of your ideas now.

**Comment by Roland-Hufnagel** [comment]
Hi. This looks good now. As an improvement you could include the Link to start a new game in your wireframe.
