### ISSUE TITLE
Quiz Form // Intro Text with 7 questions and answers

### ISSUE THREAD

**Issue by gregorsart** [alinarub/dog-app#3]
## Value proposition
**As a user** I want to start the quiz and be taken through seven questions. I can only choose one answer per question.

**In order to** find out which dog matches my needs.
## Description

![Bildschirmfoto 2023-10-12 um 11 57 52](https://github.com/alinarub/dog-app/assets/32411569/b54f2f3e-e194-4d09-a3ef-5cdf076ffc9a)
## Acceptance criteria

- [ ] On top of the page, an intro text guides the user on how to use the quiz.
- [ ] Each of the seven questions offers five different answers (via buttons).
- [ ] You have to select one answer, and you can't choose more than one.
- [ ] The selection of one answer is visually indicated by a colored border.
- [ ] Via vertical scrolling, you can get from one question to the other.
- [ ] At the end of the questions form there is a button to submit the answers.

## Tasks
- [ ] Create the feature branch `quiz-form`.
- [ ] Create the component `introText`.
- [ ] Create the component `quizForm`.
- [ ] Add 7 questions with 5 answers each.
- [ ] Make the selected answer appear with a border in the accent color.

**Comment by NikRoe** [comment]
Hi there,

this looks already very promising!

Your value proposition can be even shorter (you should not go into any specifics regarding the amount of questions).
My suggestion for the value proposition:

>  As a user 
> I want to do the quiz and be taken through several questions
> In order to find out which dog matches my needs.

In the AC I would remove the brackets for the second point. 
(In the AC you only describe the behaviour of the new feature. How you will implement this, is not important. 
_P.S.: You will most likely be working with an input element of type radio button and not with a button element_ )

Reading the AC I felt like one use case was not covered yet:
How will the form behave if a user does not answer all questions and tries to submit the quiz? 
And what happens after the form is submitted? (You could consider displaying some sort of text after completion, to give the user some sort of feedback)

Best Regards

**Comment by NikRoe** [comment]
LGTM

**Comment by alinarub** [comment]
We edited the following in the user story to match our work progress:

- We reduced the number of questions (7) and possible answers (5) down to 3 each for testing purposes.
- We cut out a design task, we will make a separate user story for the implementation of the design.
- We changed the name of the feature branch from `quiz-form` to `api-test` to better represent what we did.
- We ran tests to get familiar with the API and created a dummy data sample to initially work with.

**Comment by julialoeschel** [comment]
Hey, 
amazing, work!
only the form of the Value proposition got out of hand. 
please stick to 

As a user 
I want to do the quiz and be taken through several questions.
In order to find out which dog matches my needs.

after you fixes this, you are ready to go. 
good work!
