### ISSUE TITLE
User statistics

### ISSUE THREAD

**Issue by AchimBartscht** [alinarub/dog-app#38]
## Value proposition
**As a user** I want to find out how often the quiz was taken

**in order** to recognize the quiz traffic.

## Description
![Image](https://github.com/alinarub/dog-app/assets/32411569/e4fce28c-c9c7-4e0a-9563-d707e13373bf)

 
## Acceptance criteria
- [ ] When a quiz was taken the number of total quiz takes increases by one.

 
## Tasks
- [ ] Create the feature branch `statistics`.
- [ ] Create schema and dbconnect for MongoDB.
- [ ] Create a separate page `statistics`.
- [ ] Create a backend route with the file name `statistics` to connect to MongoDB.

**Comment by Julia-Pickel** [comment]
Hey "Dog Genie" team,
nice and clear user story! 
You might even consider highlighting the number of the quiz takers with an inline `<strong>`tag ore even the entire sentence "32 People have already taken the quiz" to catch the eye.

Keep it up 🙌
