### ISSUE TITLE
Quiz Page // Pagination

### ISSUE THREAD

**Issue by gregorsart** [alinarub/dog-app#4]
## Value proposition
**As a user** I don't want to see all 7 questions on one page.
I want each question to be displayed individually.

**In order to** focus on one question at a time.

## Description
![Bildschirmfoto 2023-10-12 um 12 16 40](https://github.com/alinarub/dog-app/assets/32411569/f21892df-2814-4a0c-b0c6-5ece1e4816b3)

## Acceptance criteria
- [ ] Even after an answer is selected you still need to confirm by clicking on the "next" button. You only can click the "next" button if you selected one answer.
- [ ] With the "previous" and "next" buttons you can see which answers you have selected. You can choose another answer by clicking on it.
- [ ] There is no "previous" button needed on the first site of the quiz.
- [ ] There is no "next" button needed on the last site of the quiz, instead there is a submit button.

## Tasks
- [ ] Create the components `previousButton` and `nextButton` - navigation is only possible when an answer is selected.
- [ ] After the last question is answered and the submit button is clicked, the user is led to the results page.

**Comment by NikRoe** [comment]
Hi there,

for the value proposition I have a suggestion:

> As a user 
> I want each question to be displayed individually
> In order to focus on one question at a time

The second Task looks to me rather like an Acceptance Criteria
There you mention a results page, does this page already exist? Otherwise you could display some sort of confirmation text for the user as a feedback, until there actually is a results page.

Something you should definitely think about is how you want to implement the pagination for the quiz. Will there be different pages (one for each question)? Or will there be a form with a question component whose content changes based on which step/question the user is on?

**Comment by NikRoe** [comment]
Hi there,

this looks good to me!

However, I would remove the last AC. This is not an important information for the App's behaviour, but for you as a team of developers.

Best regards 👋

**Comment by NikRoe** [comment]
LGTM
