### ISSUE TITLE
Random dog photo

### ISSUE THREAD

**Issue by alinarub** [alinarub/dog-app#42]
## Value proposition
**As a user** I want to be shown a random dog

**in order** to get to know more dogs from the site.

## Description

![Image](https://github.com/alinarub/dog-app/assets/137082094/bf2af050-d762-431e-a266-e4a530ae2536)

 
## Acceptance criteria
- [ ] A new random dog photo is shown on the homepage every time you refresh.
- [ ] The image is displayed underneath the button to the quiz.
- [ ] By clicking on the image, you are taken to the dog's `detail-page`.
- [ ] The image has a hover effect to show that it's clickable.
 
## Tasks
- [ ] Create feature branch `random-dog`.
- [ ] Fetch data to create a Math.random() function.
- [ ] Create a hover effect for the image.
