### ISSUE TITLE
Quiz Page // Progress Bar

### ISSUE THREAD

**Issue by gregorsart** [alinarub/dog-app#5]
## Value proposition
**As a user** I want to see the progress.

**In order to**  see how many more questions I need to answer.

## Description

![Bildschirmfoto 2023-10-12 um 12 30 51](https://github.com/alinarub/dog-app/assets/32411569/d2426483-3e84-42ac-a81c-954f06611a4f)

## Acceptance criteria
- [ ] The progress bar reflects the questions page I am currently on.

## Tasks
- [ ] Create the feature branch `progress-bar`.
- [ ] Create the component `progressBar`.

**Comment by NikRoe** [comment]
Hi there,

you could add some more information about the progress bar:
There is some visual indication in the image, you should also mention this in your user story.

Apart from that: well done 👌

**Comment by NikRoe** [comment]
LGTM 🚀
