### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by alinarub** [alinarub/dog-app#7]
## Value proposition
**As a user** I want to be introduced to the website.

**In order** to be able to take the quiz.

## Description
![Image](https://github.com/alinarub/dog-app/assets/137082094/681f1a4f-955e-4a53-9054-f29532bff956)
 
## Acceptance criteria
- [ ] The intro text quickly explains how to use the page.
- [ ] By clicking on the button you start the quiz.

 
## Tasks
- [ ] Create the feature branch `home-page`.
- [ ] Create the component `ImageTextModule`.
- [ ] Create the component `Headline`.
- [ ] Create the component `FullWidthButton`.

**Comment by willywdev** [comment]
Looks very nice!

Is this a Button or a Link that starts the quiz? Are you switching the Page or are you staying on this Page?
The Headline is a bit confusing at first. Maybe you can explain it in your Acceptance Criteria.
Suggestion: "Find your Dog - Quiz" to make it more clear how to read it. 

Greetings :)

**Comment by alinarub** [comment]
Thanks Willy! We tried to clarify it.

**Comment by willywdev** [comment]
LGTM 🚀
