### ISSUE TITLE
Hamburger Menu

### ISSUE THREAD

**Issue by AchimBartscht** [alinarub/dog-app#8]
## Value proposition
**As a user**
I want to navigate through the page. 

**In order** to jump to the desired page quickly.

## Description

![Image](https://github.com/alinarub/dog-app/assets/132458107/b8255b04-d65b-4e48-804a-73759410a45f)

 
## Acceptance criteria
- [ ] When the user clicks the hamburger menu, the menu slides in from the left side.
- [ ] In the header you see the logo on the left and the close button on the right side.
- [ ] Below that the 4 menu items are displayed.
- [ ] After that a section with a short discription is shown.
 
## Tasks
- [ ] Create the feature branch `hamburger-menu`.
- [ ] Create the component `logo`.
- [ ] Create the "close" icon.
- [ ] Create 4 links in a row.
- [ ] Insert paragraph with description text.

**Comment by julialoeschel** [comment]
Hey, 

just one thing: only display Links that lead to real pages, no pages that you gonna  build soon. 
Keep this in mind, than you are good to go. 

good job.

**Comment by AchimBartscht** [comment]
Thank you. Currently there is only the Quiz Page. We reduced the number of navigation items.

**Comment by alinarub** [comment]
We only created 3 links for the navigation so far because we haven't created the 4th page yet.
